language: node_js
node_js:
- stable
env:
  global:
    secure: FtYnyhwxNFREzNSj7pLse0F7Bmu6vcxoh8H+c5Xmj1ufuJc50FsCXmb6v3OoeHGcn7xBPC4cntx9VvT2tkK49qPmMDfCv70ITQZdEO+HDMReCd+kS162R16joi2JdnZeogez0FiaT/PFVXtCzz8UDfRzfGoX0czTTDJcKSuYwnKe7FWPfyphvzwPDTqdkkgiHaTD4bl9SYU7YBL66xWu3ElGHqTIl/O0gnNbDamAgJ+r8SOXn0IR3pZTswuTKOlE27OkJCxIJ80ZKJXCXWyduZTLFNznqRpYCGZBKOJgyqlTAKfWk5kesUksekpHhm6hlxjyyv55RtwZOcJ5BagThcNkIDv+ABuGpmzo5RAbpMhh/fboqLji8vyR+3/gWM9uh5VzN44/InrZ7ceqIAnClek3iL24gMJLt1dNb+Elbcbw2zQ7zFvnibT77vaC3nWTPm7zdMybv5FnegpmHWDTcdv/s2/nTtq/Zpec6urU657uI+BQ24e+mixBTdkQYPrjlZogsdD+CioZ8ri0LcvUjNAQi5EI1S09UPeSw5/qBcJguh1zSa4my4w6BKZfwfygETfFg/Kra9hE2fuQ8XTivR8XlrVi0JN6yl7PDu1UY3xpky8FpNysysufxnZPntzknzlzTFsAdfrI/i4aCloTcSLKhE6XBjIAzl5TAHQOBKU=
before_script:
- npm install -g gulp
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script: gulp ci
deploy:
  provider: npm
  email: calvin@digitil.me
  api_key:
    secure: SpDo6iKdYAh1GKt25L09W/xIh3gmRWJAzDQJMdJExFhTFpXpkeONc+AanKxk1gxHGwxQvpuEK6/OcdIbrulXltKhSVmTqnzSXRz07F/61BE5SuEU6fJvvnAhRc+N6UBK3lR3zuPPmtZrGgUrhjHB0PQO/1FiTQGPluBhQ5vSSRs28Ia13QDgZdSe/3Yo6mItUvwXrzEGobt+PwSzMsAvWqCDoQCtOdIkjYL2jD0+SthXFHqI+3vkETbymeh8euvW0zb3XrH50KUSh0ZWRQkcoR+niOLKrESs48bGN2xYStXMFLXCatPh3aPVOtliL2vSbZ4XPxyEcth8fh+TY5LhftbJmEDZ94eE53EMF1NWwxVTt0r+pbRZbBq4skIbmlOnxxJXtzEauSuc0jEs6mCUra+LMJSfDx715FMjjyzW2AEp1yDCYrkztNE27zlgqhiFt8k3XsE8cvtoz0OMmmZ5K2zzgW1wZ6z89Cl0wTMsjIkOcqRk2rGa2mb1O5lftAy/I6qeeu/q4Cg6dyK02SrNA6Fl+wH72bD4052N0dvP0x/5Jy4PAZalg3N0LjKaEUCc5BGwISBNdNDop0BC2EPuTb9gg+4nzXdkFQ4Trz9J9iHJrhLaUA0EhxqFfbm7OXh1oiS3uSrZIrntf9o+BxixLkfaYrwj+wxkqo4zn0JECUo=
  on:
    repo: digitil/protractor-page-objects
    branch: master
after_deploy:
- gulp publish